name: CI

on:
  workflow_dispatch:
  push:
    branches: [ master, github-workflow-test ]
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        version: ["4.24", "4.25", "4.26", "4.27", "5.0", "5.1", "5.2", "5.3"]

    steps:
      - uses: actions/checkout@v3.5.2

      - name: Run Setup Script
        run: C:\msys64\msys2_shell.cmd -defterm -here -no-start -mingw64 -shell bash setup.sh

      - name: Package for Unreal Engine
        run: python package.py "$env:UE_${{ matrix.version }}" "$env:RUNNER_TEMP"

      - name: Upload Build-Artifact
        if: startsWith(github.ref, 'refs/heads/') # Upload artifacts when commits (not tags) are pushed
        uses: actions/upload-artifact@v3.1.2
        with:
          name: UnrealLibretro-${{ matrix.version }}
          path: ${{ runner.temp }}/UnrealLibretro-${{ matrix.version }}
          if-no-files-found: error

      - name: Release
        if: startsWith(github.ref, 'refs/tags/') # Only release when a tag is pushed
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ runner.temp }}/UnrealLibretro-*.zip
